-- Migration: Create device catalog table
CREATE TABLE IF NOT EXISTS device_catalog (
  id SERIAL PRIMARY KEY,
  brand VARCHAR(100) NOT NULL,
  model VARCHAR(100) NOT NULL,
  UNIQUE(brand, model)
);

-- Seed data: popular phone models
INSERT INTO device_catalog (brand, model) VALUES
  ('Apple', 'iPhone 11'),
  ('Apple', 'iPhone 11 Pro'),
  ('Apple', 'iPhone 11 Pro Max'),
  ('Apple', 'iPhone 12'),
  ('Apple', 'iPhone 12 Mini'),
  ('Apple', 'iPhone 12 Pro'),
  ('Apple', 'iPhone 12 Pro Max'),
  ('Apple', 'iPhone 13'),
  ('Apple', 'iPhone 13 Mini'),
  ('Apple', 'iPhone 13 Pro'),
  ('Apple', 'iPhone 13 Pro Max'),
  ('Apple', 'iPhone 14'),
  ('Apple', 'iPhone 14 Plus'),
  ('Apple', 'iPhone 14 Pro'),
  ('Apple', 'iPhone 14 Pro Max'),
  ('Apple', 'iPhone 15'),
  ('Apple', 'iPhone 15 Plus'),
  ('Apple', 'iPhone 15 Pro'),
  ('Apple', 'iPhone 15 Pro Max'),
  ('Apple', 'iPhone 16'),
  ('Apple', 'iPhone 16 Pro'),
  ('Apple', 'iPhone 16 Pro Max'),
  ('Apple', 'iPhone SE (2020)'),
  ('Apple', 'iPhone SE (2022)'),
  ('Samsung', 'Galaxy S21'),
  ('Samsung', 'Galaxy S21+'),
  ('Samsung', 'Galaxy S21 Ultra'),
  ('Samsung', 'Galaxy S22'),
  ('Samsung', 'Galaxy S22+'),
  ('Samsung', 'Galaxy S22 Ultra'),
  ('Samsung', 'Galaxy S23'),
  ('Samsung', 'Galaxy S23+'),
  ('Samsung', 'Galaxy S23 Ultra'),
  ('Samsung', 'Galaxy S24'),
  ('Samsung', 'Galaxy S24+'),
  ('Samsung', 'Galaxy S24 Ultra'),
  ('Samsung', 'Galaxy A15'),
  ('Samsung', 'Galaxy A25'),
  ('Samsung', 'Galaxy A35'),
  ('Samsung', 'Galaxy A55'),
  ('Samsung', 'Galaxy A05'),
  ('Samsung', 'Galaxy A14'),
  ('Samsung', 'Galaxy A34'),
  ('Samsung', 'Galaxy A54'),
  ('Samsung', 'Galaxy Z Flip5'),
  ('Samsung', 'Galaxy Z Flip6'),
  ('Samsung', 'Galaxy Z Fold5'),
  ('Samsung', 'Galaxy Z Fold6'),
  ('Samsung', 'Galaxy Note20'),
  ('Samsung', 'Galaxy Note20 Ultra'),
  ('Xiaomi', 'Redmi Note 12'),
  ('Xiaomi', 'Redmi Note 12 Pro'),
  ('Xiaomi', 'Redmi Note 13'),
  ('Xiaomi', 'Redmi Note 13 Pro'),
  ('Xiaomi', 'Redmi Note 14'),
  ('Xiaomi', 'Redmi 13C'),
  ('Xiaomi', 'Redmi 14C'),
  ('Xiaomi', 'Poco X6'),
  ('Xiaomi', 'Poco X6 Pro'),
  ('Xiaomi', 'Poco F6'),
  ('Xiaomi', 'Poco F6 Pro'),
  ('Xiaomi', 'Xiaomi 14'),
  ('Xiaomi', 'Xiaomi 14T'),
  ('Xiaomi', 'Xiaomi 14T Pro'),
  ('Xiaomi', 'Mi 11'),
  ('Xiaomi', 'Mi 11 Lite'),
  ('Huawei', 'P60 Pro'),
  ('Huawei', 'Pura 70'),
  ('Huawei', 'Pura 70 Pro'),
  ('Huawei', 'Mate 60 Pro'),
  ('Huawei', 'Nova 12'),
  ('Huawei', 'Nova 12 Pro'),
  ('Huawei', 'Nova 13'),
  ('Huawei', 'Nova 13 Pro'),
  ('Honor', '200'),
  ('Honor', '200 Pro'),
  ('Honor', 'Magic V3'),
  ('Honor', 'X9b'),
  ('Honor', 'X8b'),
  ('Honor', '90'),
  ('Honor', '90 Lite'),
  ('OnePlus', '12'),
  ('OnePlus', '12R'),
  ('OnePlus', 'Nord 4'),
  ('OnePlus', 'Nord CE4'),
  ('Google', 'Pixel 8'),
  ('Google', 'Pixel 8 Pro'),
  ('Google', 'Pixel 9'),
  ('Google', 'Pixel 9 Pro'),
  ('Google', 'Pixel 9 Pro XL'),
  ('Google', 'Pixel 7a'),
  ('Google', 'Pixel 8a'),
  ('Realme', 'GT 6'),
  ('Realme', 'GT 6T'),
  ('Realme', '12 Pro'),
  ('Realme', '12 Pro+'),
  ('Realme', 'C65'),
  ('Realme', 'C67'),
  ('Tecno', 'Camon 30'),
  ('Tecno', 'Camon 30 Pro'),
  ('Tecno', 'Spark 20'),
  ('Tecno', 'Spark 20 Pro'),
  ('Infinix', 'Note 40'),
  ('Infinix', 'Note 40 Pro'),
  ('Infinix', 'Hot 40'),
  ('Infinix', 'Hot 40 Pro'),
  ('Nothing', 'Phone (2a)'),
  ('Nothing', 'Phone (2)'),
  ('Nothing', 'CMF Phone 1'),
  ('ASUS', 'Zenfone 11'),
  ('ASUS', 'ROG Phone 8'),
  ('ASUS', 'ROG Phone 8 Pro'),
  ('Sony', 'Xperia 1 VI'),
  ('Sony', 'Xperia 5 V'),
  ('Sony', 'Xperia 10 VI'),
  ('Oppo', 'Reno 12'),
  ('Oppo', 'Reno 12 Pro'),
  ('Oppo', 'Find X8'),
  ('Oppo', 'Find X8 Pro'),
  ('Vivo', 'V40'),
  ('Vivo', 'V40 Pro'),
  ('Vivo', 'X100'),
  ('Vivo', 'X100 Pro'),
  ('Motorola', 'Edge 50'),
  ('Motorola', 'Edge 50 Pro'),
  ('Motorola', 'Edge 50 Fusion'),
  ('Motorola', 'Moto G85'),
  ('Motorola', 'Moto G55'),
  ('Nokia', 'G42'),
  ('Nokia', 'G310'),
  ('Nokia', 'XR21'),
  ('TCL', '40 NXTPAPER'),
  ('TCL', '50 SE'),
  ('TCL', '405')
ON CONFLICT (brand, model) DO NOTHING;
