-- Migration: Seed device_catalog from CSV import
-- Source: Группы Бренд Модель ЦСВ.csv
-- Total unique entries: 74

INSERT INTO device_catalog (brand, model, group_name) VALUES
  ('Acer', 'CBG516', 'Ноутбук'),
  ('AirCool', 'FreeStyle', 'Системный блок'),
  ('Anvr', 'W1 Pro', 'Сканер отпечатков'),
  ('Apple', 'iPhone 11 Pro', 'Мобильный телефон'),
  ('Apple', 'iPad Pro 11. 4 gen A2759', 'Планшет'),
  ('Apple', 'iPhone X', 'Мобильный телефон'),
  ('Apple', 'iPhone 15 Pro', 'Мобильный телефон'),
  ('Apple', 'iPhone 13 Pro', 'Мобильный телефон'),
  ('Apple', 'iPhone 14 Pro', 'Мобильный телефон'),
  ('Apple', 'iPad Pro 12,9. Gen 5. A2379', 'Планшет'),
  ('Apple', 'Watch SE 44 mm', 'Смарт часы'),
  ('Apple', 'iPhone 13', 'Мобильный телефон'),
  ('Apple', 'iPhone 14 Pro Max', 'Мобильный телефон'),
  ('Apple', 'iPhone 7', 'Мобильный телефон'),
  ('Apple', 'A1466 MacBook Air 13-inch, 2017', 'Ноутбук'),
  ('Apple', 'MacBook Air M2 A2681', 'Ноутбук'),
  ('Apple', 'MacBook Pro 13″ A1708', 'Ноутбук'),
  ('Apple', 'iPad Pro 12.9 Gen 6 A2436', 'Планшет'),
  ('Apple', 'A2337 Air 2020', 'Ноутбук'),
  ('Apple', 'iPhone 12 Pro', 'Мобильный телефон'),
  ('Apple', 'MACBOOK (RETINA, 12-INCH, 2017) A1534', 'Ноутбук'),
  ('Apple', 'IPhone 16 Pro Max', 'Мобильный телефон'),
  ('Apple', 'iPad Air 5 A2588', 'Планшет'),
  ('Apple', 'iPhone 11', 'Мобильный телефон'),
  ('Apple', 'iPhone 11 Pro Max', 'Мобильный телефон'),
  ('Apple', 'iPhone SE (2020)', 'Мобильный телефон'),
  ('Apple', 'iPhone 14.', 'Мобильный телефон'),
  ('Apple', 'iPhone 13 Pro Max', 'Мобильный телефон'),
  ('Apple', 'A2337', 'Ноутбук'),
  ('Apple', 'MacBook (Retina, 12-inch, Early 2016)', 'Ноутбук'),
  ('Apple', 'iPad 8 A2270', 'Планшет'),
  ('ASUS', 'FX705DT', 'Ноутбук'),
  ('ASUS', 'M5406NA', 'Ноутбук'),
  ('ASUS', 'GV601R', 'Ноутбук'),
  ('ASUS', 'FX506LU', 'Ноутбук'),
  ('DeepCool', 'DC', 'Системный блок'),
  ('DJI', 'Matrice 30T', 'Дрон'),
  ('DJI', 'Mavic 2 Pro', 'Дрон'),
  ('DJI', 'Air 3s', 'Дрон'),
  ('DJI', 'Mavic Pro', 'Дрон'),
  ('DJI', 'Mini 3', 'Дрон'),
  ('DJI', 'Mini 4 Pro', 'Дрон'),
  ('DJI', 'Air 3', 'Дрон'),
  ('DJI', 'Mini 3 Pro', 'Дрон'),
  ('DJI', 'Air 2s', 'Дрон'),
  ('DJI', 'Neo', 'Дрон'),
  ('DJI', 'Mavic 3 CINE', 'Дрон'),
  ('DJI', 'Mavic 2 Pro Enterprise', 'Дрон'),
  ('DJI', 'Avata 2', 'Дрон'),
  ('HP', 'ProLiant DL20 Gen9', 'Сервер'),
  ('HP', '13-en1006ur', 'Ноутбук'),
  ('HP', 'Pavilion 15', 'Ноутбук'),
  ('Lenovo', 'ThinkPad', 'Ноутбук'),
  ('Lenovo', 'LOQ 15IRX9', 'Ноутбук'),
  ('Lenovo', 'THINKPAD X1 YOGA', 'Ноутбук'),
  ('Lenovo', 'IdeaPad L340-15API', 'Ноутбук'),
  ('Lenovo', 'Legion 5 Pro 16IAH7H', 'Ноутбук'),
  ('Lenovo', 'Legion Y530-15ICH', 'Ноутбук'),
  ('Life', 'Balance', 'Медицинский прибор'),
  ('Life', 'Contact', 'Медицинский прибор'),
  ('Life', 'Balance 2.0', 'Медицинский прибор'),
  ('Life', 'Water', 'Медицинский прибор'),
  ('MSI', 'GF63', 'Ноутбук'),
  ('Poco', 'C71', 'Мобильный телефон'),
  ('Redmi', 'Note 7', 'Мобильный телефон'),
  ('Redmi', 'note 12S', 'Мобильный телефон'),
  ('Samsung', 'S23 Ultra', 'Мобильный телефон'),
  ('Samsung', 'A34', 'Мобильный телефон'),
  ('Samsung', 'band 6', 'Смарт часы'),
  ('Samsung', 'A55', 'Мобильный телефон'),
  ('Xiaomi', 'Mi A2', 'Мобильный телефон'),
  ('ZEBRA', 'TC200J', 'Сканер'),
  ('ZEBRA', 'TC210K', 'Сканер'),
  ('ZHIYUN', 'WEEBILL 2 (CR120)', 'Стабилизатор камеры')
ON CONFLICT (brand, model) DO NOTHING;
